### ISSUE TITLE
clean does not remove all files

### ISSUE THREAD

**Issue by BrettCleary** [andresusanto/easydl#13]
On windows when running clean from `easydl/dist/utils` after finishing a download, some files are not deleted. These files are still in use by EasyDL and the following error is given `Error: EPERM: operation not permitted, stat <chunk path here>`. These files cannot be deleted manually from file explorer either. A similar error is given. 

When the program using EasyDL is closed, the files are deleted which leads me to suspect they are not being released after a download is finished by easydl. 

This is an issue because it prevents downloading the same file again since the chunk names conflict and the existing file cannot be overwritten/deleted.

**Comment by batis97** [comment]
Has your error problem "EPERM: operation not permitted, stat <chunk path here>" been resolved? If so, can you share the solution?

I have same problem too when downloading di part of chunk file

**Comment by andresusanto** [comment]
I've pushed some fixes in `v1.1.0` that might address this issue, can you retest and verify please?

**Comment by BrettCleary** [comment]
Hello `v1.1.0` did not solve this issue for me. 

I opened a PR addressing this issue here https://github.com/andresusanto/easydl/pull/18 @andresusanto @luxurycode
